const seedColors = [
    {
      paletteName: "Material UI Colors",
      id: "material-ui-colors",
      emoji: "🎨",
      colors: [
        { name: "red", hex: "F44336" },
        { name: "pink", hex: "E91E63" },
        { name: "purple", hex: "9C27B0" },
        { name: "deeppurple", hex: "673AB7" },
        { name: "indigo", hex: "3F51B5" },
        { name: "blue", hex: "2196F3" },
        { name: "lightblue", hex: "03A9F4" },
        { name: "cyan", hex: "00BCD4" },
      ],
    },
    {
      paletteName: "Material UI Colors",
      id: "material-ui-colors",
      emoji: "🎨",
      colors: [
        { name: "red", hex: "F44336" },
        { name: "pink", hex: "E91E63" },
        { name: "purple", hex: "9C27B0" },
        { name: "deeppurple", hex: "673AB7" },
        { name: "indigo", hex: "3F51B5" },
        { name: "blue", hex: "2196F3" },
        { name: "lightblue", hex: "03A9F4" },
        { name: "cyan", hex: "00BCD4" },
        { name: "teal", hex: "009688" },
      ],
    },
    {
      paletteName: "Material UI Colors",
      id: "material-ui-colors",
      emoji: "🎨",
      colors: [
        { name: "green", hex: "4CAF50" },
        { name: "lightgreen", hex: "8BC34A" },
        { name: "lime", hex: "CDDC39" },
        { name: "yellow", hex: "FFEB3B" },
        { name: "amber", hex: "FFC107" },
        { name: "orange", hex: "FF9800" },
        { name: "deeporange", hex: "FF5722" },
        { name: "brown", hex: "795548" },
        { name: "grey", hex: "9E9E9E" },
        { name: "bluegrey", hex: "607D8B" },
      ],
    },
    {
      paletteName: "Flat UI Colors v1",
      id: "flat-ui-colors-v1",
      emoji: "🤙",
      colors: [
        { name: "Carrot", hex: "e67e22" },
        { name: "Alizarin", hex: "e74c3c" },
        { name: "Clouds", hex: "ecf0f1" },
        { name: "Concrete", hex: "95a5a6" },
        { name: "Orange", hex: "f39c12" },
        { name: "Pumpkin", hex: "d35400" },
        { name: "Pomegranate", hex: "c0392b" },
        { name: "Silver", hex: "bdc3c7" },
        { name: "Asbestos", hex: "7f8c8d" },
      ],
    },
    {
      paletteName: "Flat UI Colors v1",
      id: "flat-ui-colors-v1",
      emoji: "🤙",
      colors: [
        { name: "Turquoise", hex: "1abc9c" },
        { name: "Emerald", hex: "2ecc71" },
        { name: "PeterRiver", hex: "3498db" },
        { name: "Amethyst", hex: "9b59b6" },
        { name: "WetAsphalt", hex: "34495e" },
        { name: "GreenSea", hex: "16a085" },
        { name: "Nephritis", hex: "27ae60" },
        { name: "BelizeHole", hex: "2980b9" },
        { name: "Wisteria", hex: "8e44ad" },
        { name: "MidnightBlue", hex: "2c3e50" },
      ],
    },
    {
      paletteName: "Flat UI Colors Dutch",
      id: "flat-ui-colors-dutch",
      emoji: "🇳🇱",
      colors: [
        { name: "Sunflower", hex: "FFC312" },
        { name: "Energos", hex: "C4E538" },
        { name: "HollyHock", hex: "833471" },
        { name: "RedPigment", hex: "EA2027" },
      ],
    },
    {
      paletteName: "Flat UI Colors American",
      id: "flat-ui-colors-american",
      emoji: "🇺🇸",
      colors: [
        { name: "BrightYarrow", hex: "fdcb6e" },
        { name: "OrangeVille", hex: "e17055" },
        { name: "Chi-Gong", hex: "d63031" },
        { name: "PrunusAvium", hex: "e84393" },
        { name: "DraculaOrchid", hex: "2d3436" },
      ],
    },
    {
      paletteName: "Flat UI Colors Aussie",
      id: "flat-ui-colors-aussie",
      emoji: "🇦🇺",
      colors: [
        { name: "Beekeeper", hex: "f6e58d" },
        { name: "SpicedNectarine", hex: "ffbe76" },
        { name: "PinkGlamour", hex: "ff7979" },
        { name: "JuneBud", hex: "badc58" },
        { name: "CoastalBreeze", hex: "dff9fb" },
        { name: "Turbo", hex: "f9ca24" },
        { name: "Heliotrope", hex: "e056fd" },
        { name: "ExodusFruit", hex: "686de0" },
      ],
    },
    {
      paletteName: "Flat UI Colors British",
      id: "flat-ui-colors-british",
      emoji: "🇬🇧",
      colors: [
        { name: "ProtossPylon", hex: "00a8ff" },
        { name: "Periwinkle", hex: "9c88ff" },
        { name: "Rise-N-Shine", hex: "fbc531" },
        { name: "DownloadProgress", hex: "4cd137" },
        { name: "Seabrook", hex: "487eb0" },
        { name: "VanaDylBlue", hex: "0097e6" },
        { name: "LynxWhite", hex: "f5f6fa" },
        { name: "BlueberrySoda", hex: "7f8fa6" },
        { name: "MazarineBlue", hex: "273c75" },
        { name: "BlueNights", hex: "353b48" },
      ],
    },
    {
      paletteName: "Flat UI Colors Spanish",
      id: "flat-ui-colors-spanish",
      emoji: "🇪🇸",
      colors: [
        { name: "FlourescentRed", hex: "ff5252" },
        { name: "SyntheticPumpkin", hex: "ff793f" },
        { name: "CrocodileTooth", hex: "d1ccc0" },
        { name: "MandarinSorbet", hex: "ffb142" },
        { name: "SpicedButterNut", hex: "ffda79" },
        { name: "EyeOfNewt", hex: "b33939" },
        { name: "ChileanFire", hex: "cd6133" },
        { name: "GreyPorcelain", hex: "84817a" },
        { name: "AlamedaOchre", hex: "cc8e35" },
        { name: "Desert", hex: "ccae62" },
      ],
    },
    {
      paletteName: "Flat UI Colors Indian",
      id: "flat-ui-colors-indian",
      emoji: "🇮🇳",
      colors: [
        { name: "OrchidOrange", hex: "FEA47F" },
        { name: "SpiroDiscoBall", hex: "25CCF7" },
        { name: "HoneyGlow", hex: "EAB543" },
        { name: "SweetGarden", hex: "55E6C1" },
        { name: "SasquatchSocks", hex: "FC427B" },
        { name: "PineGlade", hex: "BDC581" },
        { name: "HighlighterLavender", hex: "82589F" },
      ],
    },
    {
      paletteName: "Flat UI Colors French",
      id: "flat-ui-colors-french",
      emoji: "🇫🇷",
      colors: [
        { name: "FlatFlesh", hex: "fad390" },
        { name: "MelonMelody", hex: "f8c291" },
        { name: "Livid", hex: "6a89cc" },
        { name: "Spray", hex: "82ccdd" },
        { name: "ParadiseGreen", hex: "b8e994" },
        { name: "SquashBlossom", hex: "f6b93b" },
        { name: "MandarinRed", hex: "e55039" },
      ],
    },
  ];
  
  export default seedColors;
  